package emissions

import "cosmossdk.io/collections"

const ModuleName = "emissions"
const AlloraStakingModuleName = "allorastaking"
const AlloraRequestsModuleName = "allorarequests"

var (
	ParamsVersionKey                             = collections.NewPrefix(0)
	ParamsEpochLengthKey                         = collections.NewPrefix(1)
	ParamsEmissionsPerEpochKey                   = collections.NewPrefix(2)
	ParamsMinTopicUnmetDemandKey                 = collections.NewPrefix(3)
	ParamsMaxTopicsPerBlockKey                   = collections.NewPrefix(4)
	ParamsMinRequestUnmetDemandKey               = collections.NewPrefix(5)
	ParamsMaxAllowableMissingInferencePercentKey = collections.NewPrefix(6)
	ParamsRequiredMinimumStakeKey                = collections.NewPrefix(7)
	ParamsRemoveStakeDelayWindowKey              = collections.NewPrefix(8)
	ParamsMinFastestAllowedCadenceKey            = collections.NewPrefix(9)
	ParamsMaxInferenceRequestValidityKey         = collections.NewPrefix(10)
	ParamsMaxSlowestAllowedCadenceKey            = collections.NewPrefix(11)
	TotalStakeKey                                = collections.NewPrefix(12)
	TopicStakeKey                                = collections.NewPrefix(13)
	LastRewardsUpdateKey                         = collections.NewPrefix(14)
	RewardsKey                                   = collections.NewPrefix(15)
	NextTopicIdKey                               = collections.NewPrefix(16)
	TopicsKey                                    = collections.NewPrefix(17)
	TopicWorkersKey                              = collections.NewPrefix(18)
	TopicReputersKey                             = collections.NewPrefix(19)
	DelegatorStakeKey                            = collections.NewPrefix(20)
	BondsKey                                     = collections.NewPrefix(21)
	TargetStakeKey                               = collections.NewPrefix(22)
	WeightsKey                                   = collections.NewPrefix(23)
	InferencesKey                                = collections.NewPrefix(24)
	WorkerNodesKey                               = collections.NewPrefix(25)
	ReputerNodesKey                              = collections.NewPrefix(26)
	LatestInferencesTsKey                        = collections.NewPrefix(27)
	MempoolKey                                   = collections.NewPrefix(28)
	RequestUnmetDemandKey                        = collections.NewPrefix(29)
	TopicUnmetDemandKey                          = collections.NewPrefix(30)
	AllInferencesKey                             = collections.NewPrefix(31)
	StakeRemovalQueueKey                         = collections.NewPrefix(32)
	AllTopicStakeSumKey                          = collections.NewPrefix(33)
	AddressTopicsKey                             = collections.NewPrefix(34)
	AccumulatedMetDemandKey                      = collections.NewPrefix(35)
	NumInferencesInRewardEpochKey                = collections.NewPrefix(36)
	WhitelistAdminsKey                           = collections.NewPrefix(37)
	TopicCreationWhitelistKey                    = collections.NewPrefix(38)
	WeightSettingWhitelistKey                    = collections.NewPrefix(39)
)
