run:
  tests: false
  timeout: 5m

linters:
  disable-all: true
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default-linters
  enable:
    - asciicheck
    - bidichk
    - durationcheck
    - errcheck
    - errname
    - exportloopref
    - forcetypeassert
    - goconst
    - gofmt
    - goimports
    - goheader
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilnil
    - promlinter
    - staticcheck
    - stylecheck
    - tenv
    - thelper
    - tparallel
    - typecheck
    - thelper
    - unconvert
    - unused
    - whitespace
    - unparam
    - revive
    - gosec

linters-settings:
  revive:
    rules:
      - name: var-naming
        severity: warning
        disabled: false
        exclude: [""]
        arguments:
          - ["ID", "RPC", "IDS", "JSON"] # AllowList
          - [] # DenyList
          - - upperCaseConst: true

issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA1024: cutset contains duplicate characters" # proved to not provide much value, only false positives.
    - linters:
        - staticcheck
      text: "SA9004: only the first constant in this group has an explicit type" # explicitly recommended in go syntax
    - linters:
        - stylecheck
      text: "ST1003:" # requires identifiers with "id" to be "ID".
    - linters:
        - stylecheck
      text: "ST1005:" # punctuation in error messages
    - linters:
        - staticcheck
      text: "SA1019: \"github.com/cosmos/ibc-go/v8/modules/core/02-client/types\" is deprecated`"

      
  max-issues-per-linter: 10000
  max-same-issues: 10000

  exclude-files:
    - ".*\\.pb\\.go"
    - ".*\\.pb\\.gw\\.go"
    - ".*\\.pulsar\\.go"
    - ".*_mocks\\.go"