syntax = "proto3";
package emissions.v3;

import "gogoproto/gogo.proto";

option go_package = "github.com/allora-network/allora-chain/x/emissions/types";

message Inference {
  option (gogoproto.equal) = true;

  uint64 topic_id = 1;
  int64 block_height = 2;
  string inferer = 3;
  string value = 4 [
    (gogoproto.customtype) = "github.com/allora-network/allora-chain/math.Dec",
    (gogoproto.nullable) = false
  ];

  bytes extra_data = 5;
  string proof = 6;
}

message Inferences {
  repeated Inference inferences = 1;
}
