syntax = "proto3";
package emissions.v9;

import "amino/amino.proto";
import "cosmos_proto/cosmos.proto";
import "emissions/v3/nonce.proto";
import "emissions/v3/reputer.proto";
import "emissions/v8/params.proto";
import "emissions/v9/topic.proto";
import "gogoproto/gogo.proto";

option go_package = "github.com/allora-network/allora-chain/x/emissions/types";

// We choose a denormalized schema for events to balance the size and number of
// events, as well as the complexity of likely downstream write and read
// patterns. One likely cares about how the topic performs in totality and may
// want to update topic state after all topic information is in, or in some
// chronological order. If one normalizs by actor type, then the event volume is
// likely to be much higher and one would have to wait an undetermined amount of
// time (how many actors participated
// == how many events to wait for) to update an topic state-level metric.
// Furthermore, we know that the size of each of these messages is bounded by
// the global parameters that bound the max number of actors and topics. If one
// were to track per-actor-per-type metrics, then one immediately knows that
// they were included and participated or not in the topic at a particular block
// height as soon as one event from the topic is recorded.

enum ActorType {
  ACTOR_TYPE_INFERER_UNSPECIFIED = 0;
  ACTOR_TYPE_FORECASTER = 1;
  ACTOR_TYPE_REPUTER = 2;
}

message EventScoresSet {
  ActorType actor_type = 1;
  uint64 topic_id = 2;
  int64 block_height = 3;
  repeated string addresses = 4;
  repeated string scores = 5 [
    (gogoproto.customtype) = "github.com/allora-network/allora-chain/math.Dec",
    (gogoproto.nullable) = false
  ];
}

message EventRewardsSettled {
  ActorType actor_type = 1;
  uint64 topic_id = 2;
  int64 block_height = 3;
  repeated string addresses = 4;
  repeated string rewards = 5 [
    (gogoproto.customtype) = "github.com/allora-network/allora-chain/math.Dec",
    (gogoproto.nullable) = false
  ];
  int64 block_height_tx = 6;
}

message EventNetworkLossSet {
  uint64 topic_id = 1;
  int64 block_height = 2 [deprecated = true];
  emissions.v3.ValueBundle value_bundle = 3 [deprecated = true];
  int64 nonce = 4;
  EventValueBundle bundle = 5;
}

message EventNetworkInferences {
  uint64 topic_id = 1;
  int64 block_height = 2 [deprecated = true];
  emissions.v3.ValueBundle value_bundle = 3 [deprecated = true];
  int64 nonce = 4;
  EventValueBundle bundle = 5;
}

message EventOutlierResistantNetworkInferences {
  uint64 topic_id = 1;
  int64 nonce = 2;
  EventValueBundle bundle = 3;
}

message EventValueBundle {
  option (gogoproto.equal) = true;

  bytes extra_data = 1;
  string combined_value = 2 [
    (gogoproto.customtype) = "github.com/allora-network/allora-chain/math.Dec",
    (gogoproto.nullable) = false
  ];
  string naive_value = 3 [
    (gogoproto.customtype) = "github.com/allora-network/allora-chain/math.Dec",
    (gogoproto.nullable) = false
  ];

  repeated string inferer_addresses = 4;
  repeated string forecaster_addresses = 5;

  repeated string inferer_values = 6 [
    (gogoproto.customtype) = "github.com/allora-network/allora-chain/math.Dec",
    (gogoproto.nullable) = false
  ];
  repeated string forecaster_values = 7 [
    (gogoproto.customtype) = "github.com/allora-network/allora-chain/math.Dec",
    (gogoproto.nullable) = false
  ];
  repeated string one_out_inferer_values = 8 [
    (gogoproto.customtype) = "github.com/allora-network/allora-chain/math.Dec",
    (gogoproto.nullable) = false
  ];
  repeated string one_out_forecaster_values = 9 [
    (gogoproto.customtype) = "github.com/allora-network/allora-chain/math.Dec",
    (gogoproto.nullable) = false
  ];
  repeated string one_in_forecaster_values = 10 [
    (gogoproto.customtype) = "github.com/allora-network/allora-chain/math.Dec",
    (gogoproto.nullable) = false
  ];
  repeated string one_out_inferer_forecaster_values = 11 [
    (gogoproto.customtype) = "github.com/allora-network/allora-chain/math.DecArray",
    (gogoproto.nullable) = false
  ];
}

message EventInsertInfererPayload {
  option (gogoproto.equal) = true;
  string inferer = 1;
  int64 nonce = 2;
  uint64 topic_id = 3;
  string value = 4 [
    (gogoproto.customtype) = "github.com/allora-network/allora-chain/math.Dec",
    (gogoproto.nullable) = false
  ];
  bytes extra_data = 5;
}

message EventInsertForecasterPayload {
  option (gogoproto.equal) = true;
  string forecaster = 1;
  int64 nonce = 2;
  uint64 topic_id = 3;
  repeated string inferer_addresses = 4;
  repeated string inferer_values = 5 [
    (gogoproto.customtype) = "github.com/allora-network/allora-chain/math.Dec",
    (gogoproto.nullable) = false
  ];
  bytes extra_data = 6;
}

message EventCreateNewTopic {
  emissions.v9.Topic topic = 1;
}

message EventTopicUpdated {
  uint64 topic_id = 1;
  emissions.v9.Topic topic = 2;
}

message EventAddStake {
  uint64 topic_id = 1;
  string reputer = 2;
  string delegator = 3;
  string amount = 4 [
    (cosmos_proto.scalar) = "cosmos.Int",
    (gogoproto.customtype) = "cosmossdk.io/math.Int",
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
}

message EventRemoveStake {
  uint64 topic_id = 1;
  string reputer = 2;
  string delegator = 3;
  string amount = 4 [
    (cosmos_proto.scalar) = "cosmos.Int",
    (gogoproto.customtype) = "cosmossdk.io/math.Int",
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
}

message EventRequestStakeRemoval {
  uint64 topic_id = 1;
  string reputer = 2;
  string delegator = 3;
  string amount = 4 [
    (cosmos_proto.scalar) = "cosmos.Int",
    (gogoproto.customtype) = "cosmossdk.io/math.Int",
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
  int64 completion_height = 5;
}

message EventCancelStakeRemoval {
  uint64 topic_id = 1;
  string reputer = 2;
  string delegator = 3;
}

// EventReputerStakeUpdated is an event derived from the primitive ones EventAddStake and EventRemoveStake.
// It only expresses a change in the total stake of a reputer for a topic.
//
// Being not a primitive event, it should not be considered in an event sourcing approach, EventAddStake and EventRemoveStake should be used instead.
message EventReputerStakeUpdated {
  uint64 topic_id = 1;
  string reputer = 2;
  string amount = 3 [
    (cosmos_proto.scalar) = "cosmos.Int",
    (gogoproto.customtype) = "cosmossdk.io/math.Int",
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
}

message EventRewardDelegateStake {
  uint64 topic_id = 1;
  string reputer = 2;
  string delegator = 3;
  string amount = 4 [
    (gogoproto.customtype) = "github.com/allora-network/allora-chain/math.Dec",
    (gogoproto.nullable) = false
  ];
}

message EventInsertReputerPayload {
  uint64 topic_id = 1;
  int64 nonce = 2;
  string reputer = 3;
  EventValueBundle bundle = 5;
}

message EventReputerRegistered {
  uint64 topic_id = 1;
  string reputer = 2;
  string owner = 3;
}

message EventWorkerRegistered {
  uint64 topic_id = 1;
  string worker = 2;
  string owner = 3;
}

message EventNodeOwnerUpdated {
  string node_address = 1;
  string old_owner = 2;
  string new_owner = 3;
  bool is_reputer = 4;
}

message EventReputerUnregistered {
  uint64 topic_id = 1;
  string reputer = 2;
}

message EventWorkerUnregistered {
  uint64 topic_id = 1;
  string worker = 2;
}

message EventFundTopic {
  uint64 topic_id = 1;
  string funder = 2;
  string amount = 3 [
    (cosmos_proto.scalar) = "cosmos.Int",
    (gogoproto.customtype) = "cosmossdk.io/math.Int",
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
}

message EventParamsSet {
  emissions.v8.Params params = 1;
}

message EventWhitelistAdminAdded {
  string admin = 1;
}

message EventWhitelistAdminRemoved {
  string admin = 1;
}

message EventGlobalWhitelistAdded {
  string address = 1;
}

message EventGlobalWhitelistRemoved {
  string address = 1;
}

message EventGlobalWorkerWhitelistAdded {
  string address = 1;
}

message EventGlobalWorkerWhitelistRemoved {
  string address = 1;
}

message EventGlobalReputerWhitelistAdded {
  string address = 1;
}

message EventGlobalReputerWhitelistRemoved {
  string address = 1;
}

message EventGlobalAdminWhitelistAdded {
  string address = 1;
}

message EventGlobalAdminWhitelistRemoved {
  string address = 1;
}

message EventTopicWorkerWhitelistEnabled {
  uint64 topic_id = 1;
}

message EventTopicWorkerWhitelistDisabled {
  uint64 topic_id = 1;
}

message EventTopicReputerWhitelistEnabled {
  uint64 topic_id = 1;
}

message EventTopicReputerWhitelistDisabled {
  uint64 topic_id = 1;
}

message EventTopicCreatorWhitelistAdded {
  string address = 1;
}

message EventTopicCreatorWhitelistRemoved {
  string address = 1;
}

message EventTopicWorkerWhitelistAdded {
  uint64 topic_id = 1;
  string address = 2;
}

message EventTopicWorkerWhitelistRemoved {
  uint64 topic_id = 1;
  string address = 2;
}

message EventTopicReputerWhitelistAdded {
  uint64 topic_id = 1;
  string address = 2;
}

message EventTopicReputerWhitelistRemoved {
  uint64 topic_id = 1;
  string address = 2;
}

message EventForecastTaskScoreSet {
  uint64 topic_id = 1;
  string score = 2 [
    (gogoproto.customtype) = "github.com/allora-network/allora-chain/math.Dec",
    (gogoproto.nullable) = false
  ];
  int64 nonce_block_height = 3;
}

message EventWorkerLastCommitSet {
  uint64 topic_id = 1;
  int64 block_height = 2;
  emissions.v3.Nonce nonce = 3;
}

message EventReputerLastCommitSet {
  uint64 topic_id = 1;
  int64 block_height = 2;
  emissions.v3.Nonce nonce = 3;
}

message EventTopicRewardsSet {
  repeated uint64 topic_ids = 1;
  repeated string rewards = 2 [
    (gogoproto.customtype) = "github.com/allora-network/allora-chain/math.Dec",
    (gogoproto.nullable) = false
  ];
}

message EventEMAScoresSet {
  ActorType actor_type = 1;
  uint64 topic_id = 2;
  int64 nonce = 3;
  repeated string addresses = 4;
  repeated string scores = 5 [
    (gogoproto.customtype) = "github.com/allora-network/allora-chain/math.Dec",
    (gogoproto.nullable) = false
  ];
  repeated bool is_active = 6;
}

message EventListeningCoefficientsSet {
  ActorType actor_type = 1;
  uint64 topic_id = 2;
  int64 block_height = 3;
  repeated string addresses = 4;
  repeated string coefficients = 5 [
    (gogoproto.customtype) = "github.com/allora-network/allora-chain/math.Dec",
    (gogoproto.nullable) = false
  ];
}

message EventInfererNetworkRegretSet {
  uint64 topic_id = 1;
  int64 block_height = 2;
  repeated string addresses = 3;
  repeated string regrets = 4 [
    (gogoproto.customtype) = "github.com/allora-network/allora-chain/math.Dec",
    (gogoproto.nullable) = false
  ];
}

message EventForecasterNetworkRegretSet {
  uint64 topic_id = 1;
  int64 block_height = 2;
  repeated string addresses = 3;
  repeated string regrets = 4 [
    (gogoproto.customtype) = "github.com/allora-network/allora-chain/math.Dec",
    (gogoproto.nullable) = false
  ];
}

message EventNaiveInfererNetworkRegretSet {
  uint64 topic_id = 1;
  int64 block_height = 2;
  repeated string addresses = 3;
  repeated string regrets = 4 [
    (gogoproto.customtype) = "github.com/allora-network/allora-chain/math.Dec",
    (gogoproto.nullable) = false
  ];
}

message EventTopicInitialRegretSet {
  uint64 topic_id = 1;
  int64 block_height = 2;
  string regret = 3 [
    (gogoproto.customtype) = "github.com/allora-network/allora-chain/math.Dec",
    (gogoproto.nullable) = false
  ];
}

message EventTopicInitialEmaScoreSet {
  ActorType actor_type = 1;
  uint64 topic_id = 2;
  int64 block_height = 3;
  string score = 4 [
    (gogoproto.customtype) = "github.com/allora-network/allora-chain/math.Dec",
    (gogoproto.nullable) = false
  ];
}

message EventRegretStdNormSet {
  uint64 topic_id = 1;
  int64 block_height = 2;
  string stdnorm = 3 [
    (gogoproto.customtype) = "github.com/allora-network/allora-chain/math.Dec",
    (gogoproto.nullable) = false
  ];
}

message EventInfererWeightsSet {
  uint64 topic_id = 1;
  int64 block_height = 2;
  repeated string addresses = 3;
  repeated string weights = 4 [
    (gogoproto.customtype) = "github.com/allora-network/allora-chain/math.Dec",
    (gogoproto.nullable) = false
  ];
}

message EventForecasterWeightsSet {
  uint64 topic_id = 1;
  int64 block_height = 2;
  repeated string addresses = 3;
  repeated string weights = 4 [
    (gogoproto.customtype) = "github.com/allora-network/allora-chain/math.Dec",
    (gogoproto.nullable) = false
  ];
}

message EventPreviousPercentageRewardToStakedReputersSet {
  int64 block_height = 1;
  string percentage = 2 [
    (gogoproto.customtype) = "github.com/allora-network/allora-chain/math.Dec",
    (gogoproto.nullable) = false
  ];
}

message EventPruneRecords {
  int64 block_height = 1;
  uint64 topic_id = 2;
}

message EventDelegateRewardShareUpdated {
  uint64 topic_id = 1;
  string reputer = 2;
  string reward_per_share = 3 [
    (gogoproto.customtype) = "github.com/allora-network/allora-chain/math.Dec",
    (gogoproto.nullable) = false
  ];
}

message EventDelegateRewardDistributed {
  uint64 topic_id = 1;
  string reputer = 2;
  string amount = 3 [
    (cosmos_proto.scalar) = "cosmos.Int",
    (gogoproto.customtype) = "cosmossdk.io/math.Int",
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
}

message EventActiveReputersSet {
  uint64 topic_id = 1;
  repeated string addresses = 2;
  int64 nonce_block_height = 3;
}

message EventActiveInferersSet {
  uint64 topic_id = 1;
  repeated string addresses = 2;
  int64 nonce_block_height = 3;
}

message EventActiveForecastersSet {
  uint64 topic_id = 1;
  repeated string addresses = 2;
  int64 nonce_block_height = 3;
}

message EventTopicStatusChanged {
  uint64 topic_id = 1;
  bool is_active = 2;
}

message EventNetworkInferenceInfererWeightsSet {
  uint64 topic_id = 1;
  int64 nonce_block_height = 2;
  repeated string addresses = 3;
  repeated string weights = 4 [
    (gogoproto.customtype) = "github.com/allora-network/allora-chain/math.Dec",
    (gogoproto.nullable) = false
  ];
}

message EventNetworkInferenceForecasterWeightsSet {
  uint64 topic_id = 1;
  int64 nonce_block_height = 2;
  repeated string addresses = 3;
  repeated string weights = 4 [
    (gogoproto.customtype) = "github.com/allora-network/allora-chain/math.Dec",
    (gogoproto.nullable) = false
  ];
}

message EventNetworkInferenceInfererRegretsUsedSet {
  uint64 topic_id = 1;
  int64 nonce_block_height = 2;
  repeated string addresses = 3;
  repeated string regrets = 4 [
    (gogoproto.customtype) = "github.com/allora-network/allora-chain/math.Dec",
    (gogoproto.nullable) = false
  ];
}

message EventNetworkInferenceForecasterRegretsUsedSet {
  uint64 topic_id = 1;
  int64 nonce_block_height = 2;
  repeated string addresses = 3;
  repeated string regrets = 4 [
    (gogoproto.customtype) = "github.com/allora-network/allora-chain/math.Dec",
    (gogoproto.nullable) = false
  ];
}

message EventTopicWeightUpdated {
  uint64 topic_id = 1;
  string new_weight = 2 [
    (gogoproto.customtype) = "github.com/allora-network/allora-chain/math.Dec",
    (gogoproto.nullable) = false
  ];
  string topic_stake = 3 [
    (cosmos_proto.scalar) = "cosmos.Int",
    (gogoproto.customtype) = "cosmossdk.io/math.Int",
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
  string topic_fee_revenue = 4 [
    (cosmos_proto.scalar) = "cosmos.Int",
    (gogoproto.customtype) = "cosmossdk.io/math.Int",
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
}

message EventTopicFeeRevenueDripped {
  uint64 topic_id = 1;
  string old_revenue = 2 [
    (cosmos_proto.scalar) = "cosmos.Int",
    (gogoproto.customtype) = "cosmossdk.io/math.Int",
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
  string new_revenue = 3 [
    (cosmos_proto.scalar) = "cosmos.Int",
    (gogoproto.customtype) = "cosmossdk.io/math.Int",
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
  string drip_amount = 4 [
    (cosmos_proto.scalar) = "cosmos.Int",
    (gogoproto.customtype) = "cosmossdk.io/math.Int",
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
}

message EventWorkerSubmissionWindowOpened {
  uint64 topic_id = 1;
  int64 nonce_block_height = 2;
  int64 window_end_block = 3;
}

message EventWorkerSubmissionWindowClosed {
  uint64 topic_id = 1;
  int64 nonce_block_height = 2;
}

message EventReputerSubmissionWindowOpened {
  uint64 topic_id = 1;
  int64 nonce_block_height = 2;
  int64 window_end_block = 3;
}

message EventReputerSubmissionWindowClosed {
  uint64 topic_id = 1;
  int64 nonce_block_height = 2;
}
