syntax = "proto3";
package emissions.v9;

import "amino/amino.proto";
import "cosmos_proto/cosmos.proto";
import "gogoproto/gogo.proto";
import "emissions/v3/nonce.proto";

option go_package = "github.com/allora-network/allora-chain/x/emissions/types";

message UnbondStakeArgs {
  string delegator = 1;
  string amount = 2 [
    (cosmos_proto.scalar) = "cosmos.Int",
    (gogoproto.customtype) = "cosmossdk.io/math.Int",
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
}

message CloseWorkerNonceArgs {
  uint64 topic_id = 1;
  emissions.v3.Nonce nonce = 2;
}
