// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: emissions/v10/inputworker.proto

package types

import (
	bytes "bytes"
	fmt "fmt"
	github_com_allora_network_allora_chain_math "github.com/allora-network/allora-chain/math"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type InputInference struct {
	TopicId     uint64                                                        `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	BlockHeight int64                                                         `protobuf:"varint,2,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	Inferer     string                                                        `protobuf:"bytes,3,opt,name=inferer,proto3" json:"inferer,omitempty"`
	Value       github_com_allora_network_allora_chain_math.BoundedExp40Dec   `protobuf:"bytes,4,opt,name=value,proto3,customtype=github.com/allora-network/allora-chain/math.BoundedExp40Dec" json:"value"`
	ExtraData   []byte                                                        `protobuf:"bytes,5,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
	Proof       string                                                        `protobuf:"bytes,6,opt,name=proof,proto3" json:"proof,omitempty"`
	Values      []github_com_allora_network_allora_chain_math.BoundedExp40Dec `protobuf:"bytes,7,rep,name=values,proto3,customtype=github.com/allora-network/allora-chain/math.BoundedExp40Dec" json:"values"`
}

func (m *InputInference) Reset()         { *m = InputInference{} }
func (m *InputInference) String() string { return proto.CompactTextString(m) }
func (*InputInference) ProtoMessage()    {}
func (*InputInference) Descriptor() ([]byte, []int) {
	return fileDescriptor_122038607ddc78dd, []int{0}
}
func (m *InputInference) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InputInference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InputInference.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InputInference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputInference.Merge(m, src)
}
func (m *InputInference) XXX_Size() int {
	return m.Size()
}
func (m *InputInference) XXX_DiscardUnknown() {
	xxx_messageInfo_InputInference.DiscardUnknown(m)
}

var xxx_messageInfo_InputInference proto.InternalMessageInfo

func (m *InputInference) GetTopicId() uint64 {
	if m != nil {
		return m.TopicId
	}
	return 0
}

func (m *InputInference) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *InputInference) GetInferer() string {
	if m != nil {
		return m.Inferer
	}
	return ""
}

func (m *InputInference) GetExtraData() []byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

func (m *InputInference) GetProof() string {
	if m != nil {
		return m.Proof
	}
	return ""
}

type InputInferences struct {
	Inferences []*InputInference `protobuf:"bytes,1,rep,name=inferences,proto3" json:"inferences,omitempty"`
}

func (m *InputInferences) Reset()         { *m = InputInferences{} }
func (m *InputInferences) String() string { return proto.CompactTextString(m) }
func (*InputInferences) ProtoMessage()    {}
func (*InputInferences) Descriptor() ([]byte, []int) {
	return fileDescriptor_122038607ddc78dd, []int{1}
}
func (m *InputInferences) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InputInferences) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InputInferences.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InputInferences) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputInferences.Merge(m, src)
}
func (m *InputInferences) XXX_Size() int {
	return m.Size()
}
func (m *InputInferences) XXX_DiscardUnknown() {
	xxx_messageInfo_InputInferences.DiscardUnknown(m)
}

var xxx_messageInfo_InputInferences proto.InternalMessageInfo

func (m *InputInferences) GetInferences() []*InputInference {
	if m != nil {
		return m.Inferences
	}
	return nil
}

type InputForecastElement struct {
	Inferer string                                                      `protobuf:"bytes,1,opt,name=inferer,proto3" json:"inferer,omitempty"`
	Value   github_com_allora_network_allora_chain_math.BoundedExp40Dec `protobuf:"bytes,2,opt,name=value,proto3,customtype=github.com/allora-network/allora-chain/math.BoundedExp40Dec" json:"value"`
}

func (m *InputForecastElement) Reset()         { *m = InputForecastElement{} }
func (m *InputForecastElement) String() string { return proto.CompactTextString(m) }
func (*InputForecastElement) ProtoMessage()    {}
func (*InputForecastElement) Descriptor() ([]byte, []int) {
	return fileDescriptor_122038607ddc78dd, []int{2}
}
func (m *InputForecastElement) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InputForecastElement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InputForecastElement.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InputForecastElement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputForecastElement.Merge(m, src)
}
func (m *InputForecastElement) XXX_Size() int {
	return m.Size()
}
func (m *InputForecastElement) XXX_DiscardUnknown() {
	xxx_messageInfo_InputForecastElement.DiscardUnknown(m)
}

var xxx_messageInfo_InputForecastElement proto.InternalMessageInfo

func (m *InputForecastElement) GetInferer() string {
	if m != nil {
		return m.Inferer
	}
	return ""
}

type InputForecast struct {
	TopicId          uint64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	BlockHeight      int64                   `protobuf:"varint,2,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	Forecaster       string                  `protobuf:"bytes,3,opt,name=forecaster,proto3" json:"forecaster,omitempty"`
	ForecastElements []*InputForecastElement `protobuf:"bytes,4,rep,name=forecast_elements,json=forecastElements,proto3" json:"forecast_elements,omitempty"`
	ExtraData        []byte                  `protobuf:"bytes,5,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
}

func (m *InputForecast) Reset()         { *m = InputForecast{} }
func (m *InputForecast) String() string { return proto.CompactTextString(m) }
func (*InputForecast) ProtoMessage()    {}
func (*InputForecast) Descriptor() ([]byte, []int) {
	return fileDescriptor_122038607ddc78dd, []int{3}
}
func (m *InputForecast) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InputForecast) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InputForecast.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InputForecast) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputForecast.Merge(m, src)
}
func (m *InputForecast) XXX_Size() int {
	return m.Size()
}
func (m *InputForecast) XXX_DiscardUnknown() {
	xxx_messageInfo_InputForecast.DiscardUnknown(m)
}

var xxx_messageInfo_InputForecast proto.InternalMessageInfo

func (m *InputForecast) GetTopicId() uint64 {
	if m != nil {
		return m.TopicId
	}
	return 0
}

func (m *InputForecast) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *InputForecast) GetForecaster() string {
	if m != nil {
		return m.Forecaster
	}
	return ""
}

func (m *InputForecast) GetForecastElements() []*InputForecastElement {
	if m != nil {
		return m.ForecastElements
	}
	return nil
}

func (m *InputForecast) GetExtraData() []byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

type InputForecasts struct {
	Forecasts []*InputForecast `protobuf:"bytes,1,rep,name=forecasts,proto3" json:"forecasts,omitempty"`
}

func (m *InputForecasts) Reset()         { *m = InputForecasts{} }
func (m *InputForecasts) String() string { return proto.CompactTextString(m) }
func (*InputForecasts) ProtoMessage()    {}
func (*InputForecasts) Descriptor() ([]byte, []int) {
	return fileDescriptor_122038607ddc78dd, []int{4}
}
func (m *InputForecasts) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InputForecasts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InputForecasts.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InputForecasts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputForecasts.Merge(m, src)
}
func (m *InputForecasts) XXX_Size() int {
	return m.Size()
}
func (m *InputForecasts) XXX_DiscardUnknown() {
	xxx_messageInfo_InputForecasts.DiscardUnknown(m)
}

var xxx_messageInfo_InputForecasts proto.InternalMessageInfo

func (m *InputForecasts) GetForecasts() []*InputForecast {
	if m != nil {
		return m.Forecasts
	}
	return nil
}

type InputInferenceForecastBundle struct {
	Inference *InputInference `protobuf:"bytes,1,opt,name=inference,proto3" json:"inference,omitempty"`
	Forecast  *InputForecast  `protobuf:"bytes,2,opt,name=forecast,proto3" json:"forecast,omitempty"`
}

func (m *InputInferenceForecastBundle) Reset()         { *m = InputInferenceForecastBundle{} }
func (m *InputInferenceForecastBundle) String() string { return proto.CompactTextString(m) }
func (*InputInferenceForecastBundle) ProtoMessage()    {}
func (*InputInferenceForecastBundle) Descriptor() ([]byte, []int) {
	return fileDescriptor_122038607ddc78dd, []int{5}
}
func (m *InputInferenceForecastBundle) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InputInferenceForecastBundle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InputInferenceForecastBundle.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InputInferenceForecastBundle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputInferenceForecastBundle.Merge(m, src)
}
func (m *InputInferenceForecastBundle) XXX_Size() int {
	return m.Size()
}
func (m *InputInferenceForecastBundle) XXX_DiscardUnknown() {
	xxx_messageInfo_InputInferenceForecastBundle.DiscardUnknown(m)
}

var xxx_messageInfo_InputInferenceForecastBundle proto.InternalMessageInfo

func (m *InputInferenceForecastBundle) GetInference() *InputInference {
	if m != nil {
		return m.Inference
	}
	return nil
}

func (m *InputInferenceForecastBundle) GetForecast() *InputForecast {
	if m != nil {
		return m.Forecast
	}
	return nil
}

type InputWorkerDataBundle struct {
	Worker                             string                        `protobuf:"bytes,1,opt,name=worker,proto3" json:"worker,omitempty"`
	Nonce                              *Nonce                        `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	TopicId                            uint64                        `protobuf:"varint,3,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	InferenceForecastsBundle           *InputInferenceForecastBundle `protobuf:"bytes,4,opt,name=inference_forecasts_bundle,json=inferenceForecastsBundle,proto3" json:"inference_forecasts_bundle,omitempty"`
	InferencesForecastsBundleSignature []byte                        `protobuf:"bytes,5,opt,name=inferences_forecasts_bundle_signature,json=inferencesForecastsBundleSignature,proto3" json:"inferences_forecasts_bundle_signature,omitempty"`
	Pubkey                             string                        `protobuf:"bytes,6,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
}

func (m *InputWorkerDataBundle) Reset()         { *m = InputWorkerDataBundle{} }
func (m *InputWorkerDataBundle) String() string { return proto.CompactTextString(m) }
func (*InputWorkerDataBundle) ProtoMessage()    {}
func (*InputWorkerDataBundle) Descriptor() ([]byte, []int) {
	return fileDescriptor_122038607ddc78dd, []int{6}
}
func (m *InputWorkerDataBundle) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InputWorkerDataBundle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InputWorkerDataBundle.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InputWorkerDataBundle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputWorkerDataBundle.Merge(m, src)
}
func (m *InputWorkerDataBundle) XXX_Size() int {
	return m.Size()
}
func (m *InputWorkerDataBundle) XXX_DiscardUnknown() {
	xxx_messageInfo_InputWorkerDataBundle.DiscardUnknown(m)
}

var xxx_messageInfo_InputWorkerDataBundle proto.InternalMessageInfo

func (m *InputWorkerDataBundle) GetWorker() string {
	if m != nil {
		return m.Worker
	}
	return ""
}

func (m *InputWorkerDataBundle) GetNonce() *Nonce {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *InputWorkerDataBundle) GetTopicId() uint64 {
	if m != nil {
		return m.TopicId
	}
	return 0
}

func (m *InputWorkerDataBundle) GetInferenceForecastsBundle() *InputInferenceForecastBundle {
	if m != nil {
		return m.InferenceForecastsBundle
	}
	return nil
}

func (m *InputWorkerDataBundle) GetInferencesForecastsBundleSignature() []byte {
	if m != nil {
		return m.InferencesForecastsBundleSignature
	}
	return nil
}

func (m *InputWorkerDataBundle) GetPubkey() string {
	if m != nil {
		return m.Pubkey
	}
	return ""
}

type InputWorkerDataBundles struct {
	WorkerDataBundles []*InputWorkerDataBundle `protobuf:"bytes,1,rep,name=worker_data_bundles,json=workerDataBundles,proto3" json:"worker_data_bundles,omitempty"`
}

func (m *InputWorkerDataBundles) Reset()         { *m = InputWorkerDataBundles{} }
func (m *InputWorkerDataBundles) String() string { return proto.CompactTextString(m) }
func (*InputWorkerDataBundles) ProtoMessage()    {}
func (*InputWorkerDataBundles) Descriptor() ([]byte, []int) {
	return fileDescriptor_122038607ddc78dd, []int{7}
}
func (m *InputWorkerDataBundles) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InputWorkerDataBundles) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InputWorkerDataBundles.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InputWorkerDataBundles) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputWorkerDataBundles.Merge(m, src)
}
func (m *InputWorkerDataBundles) XXX_Size() int {
	return m.Size()
}
func (m *InputWorkerDataBundles) XXX_DiscardUnknown() {
	xxx_messageInfo_InputWorkerDataBundles.DiscardUnknown(m)
}

var xxx_messageInfo_InputWorkerDataBundles proto.InternalMessageInfo

func (m *InputWorkerDataBundles) GetWorkerDataBundles() []*InputWorkerDataBundle {
	if m != nil {
		return m.WorkerDataBundles
	}
	return nil
}

func init() {
	proto.RegisterType((*InputInference)(nil), "emissions.v10.InputInference")
	proto.RegisterType((*InputInferences)(nil), "emissions.v10.InputInferences")
	proto.RegisterType((*InputForecastElement)(nil), "emissions.v10.InputForecastElement")
	proto.RegisterType((*InputForecast)(nil), "emissions.v10.InputForecast")
	proto.RegisterType((*InputForecasts)(nil), "emissions.v10.InputForecasts")
	proto.RegisterType((*InputInferenceForecastBundle)(nil), "emissions.v10.InputInferenceForecastBundle")
	proto.RegisterType((*InputWorkerDataBundle)(nil), "emissions.v10.InputWorkerDataBundle")
	proto.RegisterType((*InputWorkerDataBundles)(nil), "emissions.v10.InputWorkerDataBundles")
}

func init() { proto.RegisterFile("emissions/v10/inputworker.proto", fileDescriptor_122038607ddc78dd) }

var fileDescriptor_122038607ddc78dd = []byte{
	// 672 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xcd, 0xe6, 0xab, 0xcd, 0xb4, 0x05, 0xba, 0x2d, 0x95, 0xa9, 0x5a, 0x27, 0x04, 0x90, 0x82,
	0x10, 0x76, 0x3f, 0x38, 0x54, 0xad, 0xb8, 0x84, 0x16, 0x51, 0x09, 0xa1, 0x62, 0x90, 0x10, 0x70,
	0xb0, 0x1c, 0x67, 0x93, 0xac, 0x9a, 0xec, 0x5a, 0x5e, 0xbb, 0x1f, 0xff, 0x02, 0xce, 0x5c, 0xf8,
	0x39, 0x3d, 0x96, 0x1b, 0x02, 0xa9, 0x42, 0x2d, 0x07, 0x7e, 0x06, 0xca, 0x7a, 0xed, 0xc4, 0xa1,
	0xb4, 0x48, 0xf4, 0xe6, 0x99, 0x7d, 0xfb, 0x76, 0xe6, 0xed, 0xdb, 0x31, 0x94, 0x49, 0x8f, 0x0a,
	0x41, 0x39, 0x13, 0xe6, 0xde, 0xf2, 0x92, 0x49, 0x99, 0x17, 0x06, 0xfb, 0xdc, 0xdf, 0x25, 0xbe,
	0xe1, 0xf9, 0x3c, 0xe0, 0x78, 0x2a, 0x01, 0x18, 0x7b, 0xcb, 0x4b, 0xf3, 0xda, 0x10, 0x7e, 0xd5,
	0x64, 0x9c, 0xb9, 0x24, 0x02, 0xce, 0xcf, 0xb6, 0x79, 0x9b, 0xcb, 0x4f, 0xb3, 0xff, 0x15, 0x65,
	0xab, 0xdf, 0xb3, 0x70, 0x6d, 0xbb, 0x4f, 0xba, 0xcd, 0x5a, 0xc4, 0x27, 0xcc, 0x25, 0xf8, 0x16,
	0x8c, 0x07, 0xdc, 0xa3, 0xae, 0x4d, 0x9b, 0x1a, 0xaa, 0xa0, 0x5a, 0xde, 0x1a, 0x93, 0xf1, 0x76,
	0x13, 0xdf, 0x86, 0xc9, 0x46, 0x97, 0xbb, 0xbb, 0x76, 0x87, 0xd0, 0x76, 0x27, 0xd0, 0xb2, 0x15,
	0x54, 0xcb, 0x59, 0x13, 0x32, 0xf7, 0x4c, 0xa6, 0xb0, 0x06, 0x63, 0x54, 0x52, 0xf9, 0x5a, 0xae,
	0x82, 0x6a, 0x25, 0x2b, 0x0e, 0xf1, 0x5b, 0x28, 0xec, 0x39, 0xdd, 0x90, 0x68, 0xf9, 0x7e, 0xbe,
	0xfe, 0xe4, 0xe8, 0xa4, 0x9c, 0xf9, 0x76, 0x52, 0xde, 0x68, 0xd3, 0xa0, 0x13, 0x36, 0x0c, 0x97,
	0xf7, 0x4c, 0xa7, 0xdb, 0xe5, 0xbe, 0xf3, 0x90, 0x11, 0xd9, 0x63, 0x1c, 0xba, 0x1d, 0x87, 0x32,
	0xb3, 0xe7, 0x04, 0x1d, 0xa3, 0xce, 0x43, 0xd6, 0x24, 0xcd, 0xad, 0x03, 0xef, 0xd1, 0xd2, 0x26,
	0x71, 0xad, 0x88, 0x11, 0x2f, 0x02, 0x90, 0x83, 0xc0, 0x77, 0xec, 0xa6, 0x13, 0x38, 0x5a, 0xa1,
	0x82, 0x6a, 0x93, 0x56, 0x49, 0x66, 0x36, 0x9d, 0xc0, 0xc1, 0xb3, 0x50, 0xf0, 0x7c, 0xce, 0x5b,
	0x5a, 0x51, 0x56, 0x14, 0x05, 0xf8, 0x3d, 0x14, 0xe5, 0x6e, 0xa1, 0x8d, 0x55, 0x72, 0x57, 0x55,
	0x90, 0xa2, 0x5c, 0xcf, 0xff, 0xfa, 0x5c, 0x46, 0xd5, 0x1d, 0xb8, 0x9e, 0x16, 0x57, 0xe0, 0xc7,
	0x00, 0x34, 0x89, 0x34, 0x54, 0xc9, 0xd5, 0x26, 0x56, 0x16, 0x8d, 0xd4, 0x25, 0x1a, 0xe9, 0x3d,
	0xd6, 0xd0, 0x86, 0xea, 0x47, 0x04, 0xb3, 0x72, 0xf9, 0x29, 0xf7, 0x89, 0xeb, 0x88, 0x60, 0xab,
	0x4b, 0x7a, 0x84, 0xa5, 0x74, 0x47, 0x7f, 0xd1, 0x3d, 0x7b, 0xd5, 0xba, 0xab, 0x2e, 0x7f, 0x22,
	0x98, 0x4a, 0xd5, 0xf4, 0x9f, 0x16, 0xd2, 0x01, 0x5a, 0x8a, 0x29, 0x71, 0xd1, 0x50, 0x06, 0xef,
	0xc0, 0x74, 0x1c, 0xd9, 0x24, 0x6a, 0x5f, 0x68, 0x79, 0xa9, 0xe4, 0x9d, 0xf3, 0x94, 0x1c, 0x91,
	0xca, 0xba, 0xd1, 0x4a, 0x27, 0xc4, 0x25, 0xfe, 0x51, 0x6d, 0x3e, 0x57, 0x2f, 0x25, 0xa6, 0x13,
	0x78, 0x1d, 0x4a, 0x31, 0x55, 0x7c, 0x95, 0x0b, 0x17, 0x15, 0x60, 0x0d, 0xe0, 0xd5, 0x4f, 0x08,
	0x16, 0xd2, 0xf7, 0x1c, 0xa3, 0xea, 0x21, 0x6b, 0x76, 0x09, 0xde, 0x80, 0x52, 0x72, 0xef, 0x52,
	0xc4, 0x4b, 0x7d, 0x32, 0xc0, 0xe3, 0x35, 0x18, 0x8f, 0x8f, 0x92, 0x0a, 0x5f, 0x56, 0x58, 0x82,
	0x56, 0xbd, 0x7e, 0xc9, 0xc2, 0x4d, 0x89, 0x78, 0x23, 0x67, 0x4d, 0x5f, 0x05, 0x55, 0xd6, 0x1c,
	0x14, 0xa3, 0xf9, 0xa3, 0x6c, 0xa6, 0x22, 0x7c, 0x1f, 0x0a, 0x72, 0xda, 0xa8, 0xe3, 0x66, 0x86,
	0x8f, 0x5b, 0x35, 0x5e, 0xf4, 0x97, 0xac, 0x08, 0x91, 0x72, 0x47, 0x2e, 0xed, 0x0e, 0x0a, 0xf3,
	0x49, 0x13, 0x76, 0x22, 0x96, 0xdd, 0x90, 0x67, 0xcb, 0xc1, 0x31, 0xb1, 0xf2, 0xe0, 0x42, 0x15,
	0xd2, 0x2a, 0x5a, 0x1a, 0x1d, 0x5d, 0x10, 0xaa, 0x91, 0x97, 0x70, 0x6f, 0xf0, 0xae, 0xfe, 0x38,
	0xcb, 0x16, 0xb4, 0xcd, 0x9c, 0x20, 0xf4, 0x89, 0xb2, 0x43, 0x75, 0x00, 0x1e, 0x61, 0x7a, 0x15,
	0x23, 0xfb, 0xda, 0x78, 0x61, 0x63, 0x97, 0x1c, 0xaa, 0x41, 0xa3, 0x22, 0xa5, 0x29, 0x83, 0xb9,
	0x73, 0x25, 0x15, 0xf8, 0x35, 0xcc, 0x44, 0x2a, 0x4a, 0xff, 0xa9, 0x0a, 0x62, 0x47, 0xdd, 0x3d,
	0xaf, 0xdd, 0x51, 0x0e, 0x6b, 0x7a, 0x7f, 0x94, 0xb5, 0x6e, 0x1d, 0x9d, 0xea, 0xe8, 0xf8, 0x54,
	0x47, 0x3f, 0x4e, 0x75, 0xf4, 0xe1, 0x4c, 0xcf, 0x1c, 0x9f, 0xe9, 0x99, 0xaf, 0x67, 0x7a, 0xe6,
	0xdd, 0xda, 0x3f, 0x3e, 0xfd, 0x03, 0x73, 0xf0, 0x37, 0x09, 0x0e, 0x3d, 0x22, 0x1a, 0x45, 0xf9,
	0xd7, 0x58, 0xfd, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x0d, 0xe2, 0x2e, 0xb1, 0x97, 0x06, 0x00, 0x00,
}

func (this *InputInference) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*InputInference)
	if !ok {
		that2, ok := that.(InputInference)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.TopicId != that1.TopicId {
		return false
	}
	if this.BlockHeight != that1.BlockHeight {
		return false
	}
	if this.Inferer != that1.Inferer {
		return false
	}
	if !this.Value.Equal(that1.Value) {
		return false
	}
	if !bytes.Equal(this.ExtraData, that1.ExtraData) {
		return false
	}
	if this.Proof != that1.Proof {
		return false
	}
	if len(this.Values) != len(that1.Values) {
		return false
	}
	for i := range this.Values {
		if !this.Values[i].Equal(that1.Values[i]) {
			return false
		}
	}
	return true
}
func (this *InputForecastElement) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*InputForecastElement)
	if !ok {
		that2, ok := that.(InputForecastElement)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Inferer != that1.Inferer {
		return false
	}
	if !this.Value.Equal(that1.Value) {
		return false
	}
	return true
}
func (this *InputForecast) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*InputForecast)
	if !ok {
		that2, ok := that.(InputForecast)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.TopicId != that1.TopicId {
		return false
	}
	if this.BlockHeight != that1.BlockHeight {
		return false
	}
	if this.Forecaster != that1.Forecaster {
		return false
	}
	if len(this.ForecastElements) != len(that1.ForecastElements) {
		return false
	}
	for i := range this.ForecastElements {
		if !this.ForecastElements[i].Equal(that1.ForecastElements[i]) {
			return false
		}
	}
	if !bytes.Equal(this.ExtraData, that1.ExtraData) {
		return false
	}
	return true
}
func (this *InputInferenceForecastBundle) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*InputInferenceForecastBundle)
	if !ok {
		that2, ok := that.(InputInferenceForecastBundle)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Inference.Equal(that1.Inference) {
		return false
	}
	if !this.Forecast.Equal(that1.Forecast) {
		return false
	}
	return true
}
func (this *InputWorkerDataBundle) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*InputWorkerDataBundle)
	if !ok {
		that2, ok := that.(InputWorkerDataBundle)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Worker != that1.Worker {
		return false
	}
	if !this.Nonce.Equal(that1.Nonce) {
		return false
	}
	if this.TopicId != that1.TopicId {
		return false
	}
	if !this.InferenceForecastsBundle.Equal(that1.InferenceForecastsBundle) {
		return false
	}
	if !bytes.Equal(this.InferencesForecastsBundleSignature, that1.InferencesForecastsBundleSignature) {
		return false
	}
	if this.Pubkey != that1.Pubkey {
		return false
	}
	return true
}
func (m *InputInference) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InputInference) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InputInference) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Values) > 0 {
		for iNdEx := len(m.Values) - 1; iNdEx >= 0; iNdEx-- {
			{
				size := m.Values[iNdEx].Size()
				i -= size
				if _, err := m.Values[iNdEx].MarshalTo(dAtA[i:]); err != nil {
					return 0, err
				}
				i = encodeVarintInputworker(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.Proof) > 0 {
		i -= len(m.Proof)
		copy(dAtA[i:], m.Proof)
		i = encodeVarintInputworker(dAtA, i, uint64(len(m.Proof)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.ExtraData) > 0 {
		i -= len(m.ExtraData)
		copy(dAtA[i:], m.ExtraData)
		i = encodeVarintInputworker(dAtA, i, uint64(len(m.ExtraData)))
		i--
		dAtA[i] = 0x2a
	}
	{
		size := m.Value.Size()
		i -= size
		if _, err := m.Value.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintInputworker(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Inferer) > 0 {
		i -= len(m.Inferer)
		copy(dAtA[i:], m.Inferer)
		i = encodeVarintInputworker(dAtA, i, uint64(len(m.Inferer)))
		i--
		dAtA[i] = 0x1a
	}
	if m.BlockHeight != 0 {
		i = encodeVarintInputworker(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x10
	}
	if m.TopicId != 0 {
		i = encodeVarintInputworker(dAtA, i, uint64(m.TopicId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *InputInferences) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InputInferences) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InputInferences) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Inferences) > 0 {
		for iNdEx := len(m.Inferences) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Inferences[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintInputworker(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *InputForecastElement) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InputForecastElement) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InputForecastElement) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Value.Size()
		i -= size
		if _, err := m.Value.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintInputworker(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Inferer) > 0 {
		i -= len(m.Inferer)
		copy(dAtA[i:], m.Inferer)
		i = encodeVarintInputworker(dAtA, i, uint64(len(m.Inferer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *InputForecast) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InputForecast) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InputForecast) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ExtraData) > 0 {
		i -= len(m.ExtraData)
		copy(dAtA[i:], m.ExtraData)
		i = encodeVarintInputworker(dAtA, i, uint64(len(m.ExtraData)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ForecastElements) > 0 {
		for iNdEx := len(m.ForecastElements) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ForecastElements[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintInputworker(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Forecaster) > 0 {
		i -= len(m.Forecaster)
		copy(dAtA[i:], m.Forecaster)
		i = encodeVarintInputworker(dAtA, i, uint64(len(m.Forecaster)))
		i--
		dAtA[i] = 0x1a
	}
	if m.BlockHeight != 0 {
		i = encodeVarintInputworker(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x10
	}
	if m.TopicId != 0 {
		i = encodeVarintInputworker(dAtA, i, uint64(m.TopicId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *InputForecasts) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InputForecasts) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InputForecasts) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Forecasts) > 0 {
		for iNdEx := len(m.Forecasts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Forecasts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintInputworker(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *InputInferenceForecastBundle) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InputInferenceForecastBundle) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InputInferenceForecastBundle) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Forecast != nil {
		{
			size, err := m.Forecast.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintInputworker(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Inference != nil {
		{
			size, err := m.Inference.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintInputworker(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *InputWorkerDataBundle) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InputWorkerDataBundle) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InputWorkerDataBundle) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Pubkey) > 0 {
		i -= len(m.Pubkey)
		copy(dAtA[i:], m.Pubkey)
		i = encodeVarintInputworker(dAtA, i, uint64(len(m.Pubkey)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.InferencesForecastsBundleSignature) > 0 {
		i -= len(m.InferencesForecastsBundleSignature)
		copy(dAtA[i:], m.InferencesForecastsBundleSignature)
		i = encodeVarintInputworker(dAtA, i, uint64(len(m.InferencesForecastsBundleSignature)))
		i--
		dAtA[i] = 0x2a
	}
	if m.InferenceForecastsBundle != nil {
		{
			size, err := m.InferenceForecastsBundle.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintInputworker(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.TopicId != 0 {
		i = encodeVarintInputworker(dAtA, i, uint64(m.TopicId))
		i--
		dAtA[i] = 0x18
	}
	if m.Nonce != nil {
		{
			size, err := m.Nonce.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintInputworker(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Worker) > 0 {
		i -= len(m.Worker)
		copy(dAtA[i:], m.Worker)
		i = encodeVarintInputworker(dAtA, i, uint64(len(m.Worker)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *InputWorkerDataBundles) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InputWorkerDataBundles) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InputWorkerDataBundles) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.WorkerDataBundles) > 0 {
		for iNdEx := len(m.WorkerDataBundles) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.WorkerDataBundles[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintInputworker(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintInputworker(dAtA []byte, offset int, v uint64) int {
	offset -= sovInputworker(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *InputInference) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TopicId != 0 {
		n += 1 + sovInputworker(uint64(m.TopicId))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovInputworker(uint64(m.BlockHeight))
	}
	l = len(m.Inferer)
	if l > 0 {
		n += 1 + l + sovInputworker(uint64(l))
	}
	l = m.Value.Size()
	n += 1 + l + sovInputworker(uint64(l))
	l = len(m.ExtraData)
	if l > 0 {
		n += 1 + l + sovInputworker(uint64(l))
	}
	l = len(m.Proof)
	if l > 0 {
		n += 1 + l + sovInputworker(uint64(l))
	}
	if len(m.Values) > 0 {
		for _, e := range m.Values {
			l = e.Size()
			n += 1 + l + sovInputworker(uint64(l))
		}
	}
	return n
}

func (m *InputInferences) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Inferences) > 0 {
		for _, e := range m.Inferences {
			l = e.Size()
			n += 1 + l + sovInputworker(uint64(l))
		}
	}
	return n
}

func (m *InputForecastElement) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Inferer)
	if l > 0 {
		n += 1 + l + sovInputworker(uint64(l))
	}
	l = m.Value.Size()
	n += 1 + l + sovInputworker(uint64(l))
	return n
}

func (m *InputForecast) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TopicId != 0 {
		n += 1 + sovInputworker(uint64(m.TopicId))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovInputworker(uint64(m.BlockHeight))
	}
	l = len(m.Forecaster)
	if l > 0 {
		n += 1 + l + sovInputworker(uint64(l))
	}
	if len(m.ForecastElements) > 0 {
		for _, e := range m.ForecastElements {
			l = e.Size()
			n += 1 + l + sovInputworker(uint64(l))
		}
	}
	l = len(m.ExtraData)
	if l > 0 {
		n += 1 + l + sovInputworker(uint64(l))
	}
	return n
}

func (m *InputForecasts) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Forecasts) > 0 {
		for _, e := range m.Forecasts {
			l = e.Size()
			n += 1 + l + sovInputworker(uint64(l))
		}
	}
	return n
}

func (m *InputInferenceForecastBundle) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Inference != nil {
		l = m.Inference.Size()
		n += 1 + l + sovInputworker(uint64(l))
	}
	if m.Forecast != nil {
		l = m.Forecast.Size()
		n += 1 + l + sovInputworker(uint64(l))
	}
	return n
}

func (m *InputWorkerDataBundle) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Worker)
	if l > 0 {
		n += 1 + l + sovInputworker(uint64(l))
	}
	if m.Nonce != nil {
		l = m.Nonce.Size()
		n += 1 + l + sovInputworker(uint64(l))
	}
	if m.TopicId != 0 {
		n += 1 + sovInputworker(uint64(m.TopicId))
	}
	if m.InferenceForecastsBundle != nil {
		l = m.InferenceForecastsBundle.Size()
		n += 1 + l + sovInputworker(uint64(l))
	}
	l = len(m.InferencesForecastsBundleSignature)
	if l > 0 {
		n += 1 + l + sovInputworker(uint64(l))
	}
	l = len(m.Pubkey)
	if l > 0 {
		n += 1 + l + sovInputworker(uint64(l))
	}
	return n
}

func (m *InputWorkerDataBundles) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.WorkerDataBundles) > 0 {
		for _, e := range m.WorkerDataBundles {
			l = e.Size()
			n += 1 + l + sovInputworker(uint64(l))
		}
	}
	return n
}

func sovInputworker(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozInputworker(x uint64) (n int) {
	return sovInputworker(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *InputInference) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInputworker
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InputInference: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InputInference: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TopicId", wireType)
			}
			m.TopicId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInputworker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TopicId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInputworker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Inferer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInputworker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInputworker
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInputworker
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Inferer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInputworker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInputworker
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInputworker
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Value.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExtraData", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInputworker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthInputworker
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthInputworker
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExtraData = append(m.ExtraData[:0], dAtA[iNdEx:postIndex]...)
			if m.ExtraData == nil {
				m.ExtraData = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInputworker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInputworker
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInputworker
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proof = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Values", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInputworker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInputworker
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInputworker
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_allora_network_allora_chain_math.BoundedExp40Dec
			m.Values = append(m.Values, v)
			if err := m.Values[len(m.Values)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInputworker(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthInputworker
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InputInferences) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInputworker
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InputInferences: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InputInferences: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Inferences", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInputworker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInputworker
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInputworker
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Inferences = append(m.Inferences, &InputInference{})
			if err := m.Inferences[len(m.Inferences)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInputworker(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthInputworker
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InputForecastElement) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInputworker
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InputForecastElement: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InputForecastElement: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Inferer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInputworker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInputworker
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInputworker
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Inferer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInputworker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInputworker
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInputworker
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Value.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInputworker(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthInputworker
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InputForecast) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInputworker
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InputForecast: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InputForecast: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TopicId", wireType)
			}
			m.TopicId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInputworker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TopicId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInputworker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Forecaster", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInputworker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInputworker
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInputworker
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Forecaster = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ForecastElements", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInputworker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInputworker
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInputworker
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ForecastElements = append(m.ForecastElements, &InputForecastElement{})
			if err := m.ForecastElements[len(m.ForecastElements)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExtraData", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInputworker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthInputworker
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthInputworker
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExtraData = append(m.ExtraData[:0], dAtA[iNdEx:postIndex]...)
			if m.ExtraData == nil {
				m.ExtraData = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInputworker(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthInputworker
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InputForecasts) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInputworker
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InputForecasts: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InputForecasts: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Forecasts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInputworker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInputworker
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInputworker
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Forecasts = append(m.Forecasts, &InputForecast{})
			if err := m.Forecasts[len(m.Forecasts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInputworker(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthInputworker
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InputInferenceForecastBundle) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInputworker
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InputInferenceForecastBundle: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InputInferenceForecastBundle: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Inference", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInputworker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInputworker
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInputworker
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Inference == nil {
				m.Inference = &InputInference{}
			}
			if err := m.Inference.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Forecast", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInputworker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInputworker
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInputworker
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Forecast == nil {
				m.Forecast = &InputForecast{}
			}
			if err := m.Forecast.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInputworker(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthInputworker
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InputWorkerDataBundle) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInputworker
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InputWorkerDataBundle: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InputWorkerDataBundle: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Worker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInputworker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInputworker
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInputworker
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Worker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInputworker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInputworker
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInputworker
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Nonce == nil {
				m.Nonce = &Nonce{}
			}
			if err := m.Nonce.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TopicId", wireType)
			}
			m.TopicId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInputworker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TopicId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InferenceForecastsBundle", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInputworker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInputworker
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInputworker
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.InferenceForecastsBundle == nil {
				m.InferenceForecastsBundle = &InputInferenceForecastBundle{}
			}
			if err := m.InferenceForecastsBundle.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InferencesForecastsBundleSignature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInputworker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthInputworker
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthInputworker
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InferencesForecastsBundleSignature = append(m.InferencesForecastsBundleSignature[:0], dAtA[iNdEx:postIndex]...)
			if m.InferencesForecastsBundleSignature == nil {
				m.InferencesForecastsBundleSignature = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pubkey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInputworker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInputworker
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInputworker
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pubkey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInputworker(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthInputworker
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InputWorkerDataBundles) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInputworker
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InputWorkerDataBundles: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InputWorkerDataBundles: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WorkerDataBundles", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInputworker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInputworker
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInputworker
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WorkerDataBundles = append(m.WorkerDataBundles, &InputWorkerDataBundle{})
			if err := m.WorkerDataBundles[len(m.WorkerDataBundles)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInputworker(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthInputworker
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipInputworker(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowInputworker
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowInputworker
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowInputworker
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthInputworker
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupInputworker
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthInputworker
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthInputworker        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowInputworker          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupInputworker = fmt.Errorf("proto: unexpected end of group")
)
