syntax = "proto3";
package scheduler.v1;

import "gogoproto/gogo.proto";
import "google/protobuf/any.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";

option go_package = "github.com/allora-network/allora-chain/x/scheduler/types";

message Task {
  option (gogoproto.equal) = true;

  // id is the unique identifier for the task.
  string id = 1 [
    (gogoproto.nullable) = false,
    (gogoproto.customtype) = "TaskID"
  ];

  // typename is the type of the task, which determines how it is executed.
  string typename = 2;

  // args is the arguments for the task. The format depends on the task type.
  google.protobuf.Any args = 3;

  // scheduled_for is the timestamp of the currently scheduled run for the task. If empty, the task is not scheduled (i.e. it's paused).
  google.protobuf.Timestamp scheduled_for = 4 [(gogoproto.stdtime) = true];

  // interval is the duration between task runs. If empty, the task runs only once. If set, the task is considered periodic.
  google.protobuf.Duration interval = 5 [(gogoproto.stdduration) = true];

  // last_run_at is the timestamp of the last time the task was run. If the task has never run, this is empty.
  google.protobuf.Timestamp last_run_at = 6 [(gogoproto.stdtime) = true];

  // run_count is the number of times the task has been run.
  uint64 run_count = 7;

  // scheduling_strategy defines how the next run time is calculated after each execution.
  SchedulingStrategy scheduling_strategy = 8;
}

// SchedulingStrategy defines the scheduling behaviour of a task, it is only useful in the context of a periodic task,
// and affects how the next run time is calculated after each execution.
enum SchedulingStrategy {
  // RELATIVE means the next run time is calculated relative to the current time, i.e. scheduled_for = now + interval.
  // This is the default behaviour.
  RELATIVE = 0;

  // ABSOLUTE means the next run time is calculated relative to the last scheduled run time, i.e. scheduled_for = last_run_at + interval.
  ABSOLUTE = 1;
}
